Repository cowprotocol/watch-tower, pull requests merged in 2023-10, with the labels that each got.

#75 feat: observability (api, metrics, and startup / liveliness probes)
  package.json
  src/commands/run.ts
  src/domain/addContract.ts
  src/domain/chainContext.ts
  src/domain/checkForAndPlaceOrder.ts
  src/index.ts
  src/types/index.ts
  src/types/model.ts
  src/utils/api.ts
  src/utils/metrics.ts
  yarn.lock
Labels: enhancement, E:1.2: Watch Tower Service

#92 chore: api and version polish
  README.md
  src/commands/run.ts
  src/index.ts
  src/types/index.ts
  src/utils/api.ts
  src/utils/db.ts
  src/utils/logging.ts
Labels: enhancement, E:1.2: Watch Tower Service

#93 fix: configurable watchdog timeout
  src/commands/run.ts
  src/domain/chainContext.ts
  src/index.ts
  src/types/index.ts
Labels: bug

#94 fix: drop incompatible orders
  src/domain/checkForAndPlaceOrder.ts
  src/utils/contracts.ts
  src/utils/misc.ts
  src/utils/utils.spec.ts
Labels: bug

#95 chore: metrics todo and naming
  package.json
  src/domain/addContract.ts
  src/domain/chainContext.ts
  src/domain/checkForAndPlaceOrder.ts
  src/types/model.ts
  src/utils/api.ts
  src/utils/contracts.ts
  src/utils/metrics.ts
  src/utils/utils.spec.ts
  yarn.lock
Labels: enhancement, infra, E:1.2: Watch Tower Service

#96 chore: health probe
  src/domain/chainContext.ts
  src/types/model.ts
  src/utils/api.ts
  src/utils/context.ts
Labels: enhancement, infra, E:1.2: Watch Tower Service

#109 chore: cleanup repo, readme, add cli script
  .env.example
  .github/ISSUE_TEMPLATE/bug_report.md
  README.md
  package.json
  src/commands/dumpDb.ts
  src/commands/run.ts
  src/domain/checkForAndPlaceOrder.ts
  src/index.ts
  src/types/index.ts
  src/types/model.ts
  src/utils/db.ts
Labels: documentation, E:1.2: Watch Tower Service

#114 chore: reduce logged errors
  src/domain/checkForAndPlaceOrder.ts
Labels: E:1.2: Watch Tower Service
