Repository cowprotocol/watch-tower, pull requests merged in 2023-09, with the labels that each got.

#31 Optimise stored state
  actions/checkForAndPlaceOrder.ts
Labels: enhancement

#29 feat: state rebuilder
  README.md
  actions/checkForAndPlaceOrder.ts
  actions/model.ts
  actions/test/run_local.ts
Labels: enhancement, E:2023-composable-cow

#37 refactor: remove tenderly
  .eslintrc.json
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  abi/ComposableCoW.json
  abi/ExtensibleFallbackHandler.json
  abi/GPv2Settlement.json
  abi/Multicall3.json
  actions/package-lock.json
  actions/package.json
  actions/yarn.lock
  commitlint.config.js
  package-lock.json
  package.json
  src/addContract.ts
  src/checkForAndPlaceOrder.ts
  src/checkForSettlement.ts
  src/model.ts
  src/test/run_local.ts
  src/utils.spec.ts
  src/utils/context.ts
  src/utils/contracts.ts
  src/utils/index.ts
  src/utils/logging.ts
  src/utils/misc.ts
  src/utils/poll.ts
  src/utils/provider.ts
  tenderly-prod.yaml
  tenderly.yaml
  tsconfig.json
  yarn.lock
Labels: infra

#53 refactor: context
  package.json
  src/addContract.ts
  src/checkForAndPlaceOrder.ts
  src/modes/run.ts
  src/types/model.ts
  src/utils/context.ts
Labels: enhancement

#66 feat: watchdog
  src/domain/chainContext.ts
Labels: enhancement, E:1.2: Watch Tower Service

#69 feat: increase log level for specific modules
  README.md
  src/commands/dumpDb.ts
  src/commands/run.ts
  src/domain/addContract.ts
  src/domain/chainContext.ts
  src/domain/checkForAndPlaceOrder.ts
  src/index.ts
  src/utils/context.ts
  src/utils/logging.ts
  src/utils/poll.ts
Labels: E:1.2: Watch Tower Service
